#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gnome2-Canvas
abstract:     (DEPRECATED) A structured graphics canvas
version:      1.006
version_from: Canvas.pm
installdirs:  site
requires:
configure_requires:
  Gtk2: 1.100
  ExtUtils::Depends: '0.2'
  ExtUtils::MakeMaker: '0'
  ExtUtils::PkgConfig: '1.03'
  Glib: '1.120'
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
x_deprecated: 1
