#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gnome2-Canvas
version:      1.002
version_from: Canvas.pm
installdirs:  site
requires:
configure_requires:
  Gtk2: 1.100

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
